# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1
parameters:
  deployment_id:
    type: string
    default: ""
  project_id:
    type: string
    default: ""
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
jobs:
  build-repo:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/guides/execution-managed/executor-intro/ & https://circleci.com/docs/reference/configuration-reference/#executor-job
    docker:
      - image: amal664/lynfera-builds
    environment:
      DEPLOYMENT_ID: << pipeline.parameters.deployment_id >>
      PROJECT_ID: << pipeline.parameters.project_id >>
    steps:
      - checkout
      - run:
          name: Container check
          command: |
            echo "Container is running....."

      - run:
          name: Build notice
          command: |
            echo "::notice::Building project => $PROJECT_ID --- deployment => $DEPLOYMENT_ID"

      - run:
          name: Run build entrypoint
          command: |
            /home/app/main.sh

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  build-repo-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-repo
