name: On-demand Build
run-name: Build ${{ github.event.client_payload.projectId }} â€“ ${{ github.event.client_payload.deploymentId }}
on:
  repository_dispatch:
    types: [run-build]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: amal664/lynfera-builds
      options: >-
        --memory=2g
        --cpus=2
        --entrypoint ""
    env:
      DEPLOYMENT_ID: ${{ github.event.client_payload.deploymentId }}
      PROJECT_ID: ${{ github.event.client_payload.projectId }}
      SERVICE_TOKEN: ${{ github.event.client_payload.serviceToken }}
      CLOUD_BUCKET: ${{ secrets.CLOUD_BUCKET }}
      STORAGE_SERVER_ENDPOINT: ${{ secrets.STORAGE_SERVER_ENDPOINT }}
      API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
    steps:
      - name: Run commands in container
        run: |
          echo "Container is running....."
      - name: Run commands in container
        run: |
          echo "::notice::Building project $PROJECT_ID"
      - name: Run build entrypoint
        run:  |
          printf "%s\n%s\n%s\n%s\n%s\n%s\n" \
            "${{ secrets.CONTAINER_API_TOKEN }}" \
            "${{ secrets.CLOUD_ACCESSKEY }}" \
            "${{ secrets.CLOUD_SECRETKEY }}" \
            "${{ secrets.CLOUD_ENDPOINT }}" \
            "${{ secrets.KAFKA_USERNAME }}" \
            "${{ secrets.KAFKA_PASSWORD }}" | node /app/builder.js

          
  error_handle:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install kafkajs@2.2.4

      - name: Report starting error
        env:
          KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
          KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
          DEPLOYMENT_ID: ${{ github.event.client_payload.deploymentId }}
          PROJECT_ID: ${{ github.event.client_payload.projectId }}
        run: node scripts/errorHandler.js
